feat(eth-staking): add unstake pending state, pool stats, stake data …
everstake/trezor-suite pull request #10
Opened 2024-02-03 12:23 UTC by shotgunofdeath

## Description

The pending unstake state is added to the staking tab dashboard.
The progress bar is updated accordingly to the pending unstake state.
All fiat related data is hidden when rates are unavailable.
Stake, unstake, claim balances are fetched from Blockbook.
StakingCard is refactored.
Limits validation in the stake and unstake forms is fixed. Now it operates with BigNumber instead of native JS numbers. This caused decimals and scientific notation problems.
Evestake pool stats are added (APY + Next reward payout).
The successful claim notification is added.

## Related Issue

Resolve 
https://github.com/trezor/trezor-suite/issues/9280
https://github.com/trezor/trezor-suite/issues/9246

## Screenshots:
<img width="1501" alt="Знімок екрана 2024-02-03 о 12 53 50" src="https://github.com/everstake/trezor-suite/assets/42133844/10ed9387-5b76-4d4f-b27e-242659884c22">
<img width="1501" alt="Знімок екрана 2024-02-03 о 12 56 04" src="https://github.com/everstake/trezor-suite/assets/42133844/8e814f0b-ed10-4816-9715-31d84d0129d7">
<img width="1501" alt="Знімок екрана 2024-02-03 о 12 57 14" src="https://github.com/everstake/trezor-suite/assets/42133844/b735d958-09db-48c1-bf23-36dfed8d7981">
<img width="1501" alt="Знімок екрана 2024-02-03 о 12 57 23" src="https://github.com/everstake/trezor-suite/assets/42133844/74b94d33-f304-4d11-8eee-7b6c137f07d3">

2024-02-04 13:21 UTC, tomasklim requested changes
I was able to claim when claim button was not available in UI anymore
1. 0.12345 THOL was ready to claim
2. I unstaked 0.1 THOL
3. Before the transaction was confirmed, I opened claim modal
4. When it was confirmed, I claimed the balance
5. Success. Is it ok?

Let's say, that I stake 1 THOL, I unstake 0.95. 0.05 THOL is there, which I cannot unstake because of 0.1 limit
![Screenshot 2024-02-04 at 13 38 39](https://github.com/everstake/trezor-suite/assets/33235762/45771a73-908f-4684-af7e-bba84e9a138a)

Also when you check the image above, when Stake, rewards, and unstaking does not fit, it would be nice to put them under each other

2024-02-04 13:21 UTC, tomasklim commented on suite-common/wallet-utils/src/accountUtils.ts
> +const areStakingPoolsEqual = (a1: StakingPool[] | undefined, a2: StakingPool[] | undefined) => {
Do you think that comparison like

```
    return JSON.stringify(a1) === JSON.stringify(a2);
``` 
is not enough?

2024-02-04 13:21 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/hooks/useEverstakePoolStats.ts
> +        const getEeverstakePoolStats = async () => {
```suggestion
        const getEverstakePoolStats = async () => {
```

2024-02-04 13:21 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/hooks/useEverstakePoolStats.ts
> +export const useEverstakePoolStats = () => {
You forgot to use this hook in `StakeEthCard` and `EmptyStakingCard` for live `apy`

2024-02-04 13:21 UTC, tomasklim commented on packages/suite/src/components/wallet/WalletLayout/AccountBanners/StakeEthBanner.tsx
> +                            <Translation id="TR_STAKE_ANY_AMOUNT_ETH" values={{ apyPercent: 5 }} />
data from `useEverstakePoolStats`?

2024-02-04 13:21 UTC, tomasklim commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ClaimModal/ClaimEthForm.tsx
> +                <Translation id="TR_STAKE_IN_NEXT_BLOCK" />
TR_STAKE_CLAIM_IN_NEXT_BLOCK

2024-02-04 13:22 UTC, tomasklim commented on suite-common/wallet-utils/src/accountUtils.ts
> +const areStakingPoolsEqual = (a1: StakingPool[] | undefined, a2: StakingPool[] | undefined) => {
If not, just please use different name for variables `a1` and `a2`

2024-02-05 11:43 UTC, omykhailovskyi commented
> I was able to claim when claim button was not available in UI anymore
> 
> 1. 0.12345 THOL was ready to claim
> 2. I unstaked 0.1 THOL
> 3. Before the transaction was confirmed, I opened claim modal
> 4. When it was confirmed, I claimed the balance
> 5. Success. Is it ok?
> 
> Let's say, that I stake 1 THOL, I unstake 0.95. 0.05 THOL is there, which I cannot unstake because of 0.1 limit ![Screenshot 2024-02-04 at 13 38 39](https://private-user-images.githubusercontent.com/33235762/302105583-45771a73-908f-4684-af7e-bba84e9a138a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzMzOTUsIm5iZiI6MTcwNzEzMzA5NSwicGF0aCI6Ii8zMzIzNTc2Mi8zMDIxMDU1ODMtNDU3NzFhNzMtOTA4Zi00Njg0LWFmN2UtYmJhODRlOWExMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDc1YWM2MzY4YjE1ZjEyZTUxOGIyNzc0MmVhNDdlNjJiMDUzNTdmNWI3ODMwMmUxMjdkZGJmMTdmZTVlM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lebRE_QeCW2pZ5KARSnYlXUIlU6Os73D6EnHZgL2NPo)
> 
> Also when you check the image above, when Stake, rewards, and unstaking does not fit, it would be nice to put them under each other

Hey, @tomasklim 
Answering your question, think it's fine, but we can discuss in voice.
So basically we at the moment provide possibility to claim ready to claim balance, but to avoid user to spend more on tx fee, he claims all amount.
For the case if user already has ready to claim balance we represent it on the Unstake Modal form
<img width="778" alt="image" src="https://github.com/everstake/trezor-suite/assets/134495539/1c9cb499-34be-47c4-9bf1-63d98ed672b6">
Please check if it's fine.

Currently we have a min unstake amount and it's the same as min stake amount (0.1 ETH) to minimize spam activities.

2024-02-06 09:50 UTC, shotgunofdeath commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ClaimModal/ClaimEthForm.tsx
> +                <Translation id="TR_STAKE_IN_NEXT_BLOCK" />
https://github.com/everstake/trezor-suite/pull/10/commits/81f13c29cc0a25435fad0c613489f4a7942b1dcb

2024-02-06 09:50 UTC, shotgunofdeath commented on packages/suite/src/components/wallet/WalletLayout/AccountBanners/StakeEthBanner.tsx
> +                            <Translation id="TR_STAKE_ANY_AMOUNT_ETH" values={{ apyPercent: 5 }} />
I actually thought about it, but then I saw the text with the "up to" wording there and thought that it should be static data. Should I use the dynamic value anyway?

2024-02-06 09:50 UTC, shotgunofdeath commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/hooks/useEverstakePoolStats.ts
> +export const useEverstakePoolStats = () => {
I actually thought about it, but then I saw the text with the "up to" wording there and thought that it should be static data. Should I use the dynamic value anyway?

2024-02-06 09:50 UTC, shotgunofdeath commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/hooks/useEverstakePoolStats.ts
> +        const getEeverstakePoolStats = async () => {
https://github.com/everstake/trezor-suite/pull/10/commits/81f13c29cc0a25435fad0c613489f4a7942b1dcb

2024-02-06 09:50 UTC, shotgunofdeath commented on suite-common/wallet-utils/src/accountUtils.ts
> +const areStakingPoolsEqual = (a1: StakingPool[] | undefined, a2: StakingPool[] | undefined) => {
If the order of the fields inside `stakingPools` objects is guaranteed and data there will always be of a `string` type, then it should be enough, yes.

https://github.com/everstake/trezor-suite/pull/10/commits/81f13c29cc0a25435fad0c613489f4a7942b1dcb

2024-02-07 12:52 UTC, omykhailovskyi commented
@shotgunofdeath Move Claim message in the top before Only rewards line

2024-02-07 13:18 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/hooks/useEverstakePoolStats.ts
> +export const useEverstakePoolStats = () => {
Let's see the result here https://satoshilabs.slack.com/archives/C0543DJBK0C/p1707311776921939

2024-02-07 13:18 UTC, tomasklim approved these changes

2024-02-12 08:37 UTC, merged