feat(eth-staking): add stake and claim txs states change
everstake/trezor-suite pull request #9
Opened 2024-01-26 15:58 UTC by shotgunofdeath

## Description

State changes for the progress labels when a stake tx is in progress are added.
State changes for the claim card when  a claim tx is in progress are added.

## Related Issue

Resolve 
https://github.com/trezor/trezor-suite/issues/9272
https://github.com/trezor/trezor-suite/issues/9268
https://github.com/trezor/trezor-suite/issues/9284

## Screenshots:

2024-01-27 15:14 UTC, tomasklim requested changes

2024-01-27 15:14 UTC, tomasklim commented on packages/suite-desktop-core/src/config.ts
> +    'eth-api-b2c.everstake.one',
When you migrate to Blockbook balances, what backends will be needed, just `eth-api-b2c.everstake.one` or will you still need to do some RPC calls?

2024-01-27 15:14 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingCard.tsx
> +        const sevenDays = 604800;
nit:
```suggestion
        const sevenDays = 7 * 24 * 60 * 60;
```

2024-01-27 15:14 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/useValidatorsQueue.ts
> +export const useValidatorsQueue = () => {
Add some loading state and error handling for UI in case that fetching fails

<img width="684" alt="Screenshot 2024-01-27 at 14 01 28" src="https://github.com/everstake/trezor-suite/assets/33235762/5676243d-f44a-429c-9544-7e2d7db2fe17">

2024-01-29 11:49 UTC, shotgunofdeath commented on packages/suite-desktop-core/src/config.ts
> +    'eth-api-b2c.everstake.one',
I guess both these endpoints will still be needed. They are not RPC calls. Production endpoint will not work on localhost, therefore the stage one should be used for that purpose (with VPN).

2024-01-29 11:49 UTC, shotgunofdeath commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingCard.tsx
> +        const sevenDays = 604800;
https://github.com/everstake/trezor-suite/pull/9/commits/53c0e6b68c2b404c6dba17b7ca5b5f1dd6e98f15

2024-01-29 11:49 UTC, shotgunofdeath commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/useValidatorsQueue.ts
> +export const useValidatorsQueue = () => {
Done. Added loading states. As for the error handling, I just hide the info about days is there's no correct data. Let me know if you have better ideas, please.

https://github.com/everstake/trezor-suite/pull/9/commits/53c0e6b68c2b404c6dba17b7ca5b5f1dd6e98f15

2024-01-30 08:05 UTC, tomasklim commented on packages/suite-desktop-core/src/config.ts
> +    'eth-api-b2c.everstake.one',
Got it, and how about
```    
eth-goerli.public.blastapi.io
ethereum-holesky.publicnode.com
mainnet.infura.io
```

Is the question about if you can send RPC calls to BlockBook still relevant?

2024-01-30 08:05 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/useValidatorsQueue.ts
> +export const useValidatorsQueue = () => {
Makes total sense to me

2024-01-30 08:24 UTC, tomasklim approved these changes

2024-01-30 08:31 UTC, tomasklim commented
I found out why I had an empty fiat rate even though you use ETH price. It is because I did not have Ethereum enabled, so the rate was not fetched 😀
![Screenshot 2024-01-30 at 9 21 06](https://github.com/everstake/trezor-suite/assets/33235762/f06491ab-5992-425a-a379-b1676845b790)
![Screenshot 2024-01-30 at 9 21 18](https://github.com/everstake/trezor-suite/assets/33235762/2c2150c0-c547-47ab-96ab-b2dc512765fc)

So it would be great to put there logic to not show it when fiat rate is not available. I know that it will not be visible for testnets, but if coingecko api fails for us, it will look weird also fot mainet.

2024-01-30 09:27 UTC, shotgunofdeath commented on packages/suite-desktop-core/src/config.ts
> +    'eth-api-b2c.everstake.one',
I guess the question is still relevant. Our team wants to discuss it tomorrow during the call.

2024-01-30 09:32 UTC, shotgunofdeath commented
Aha, got it! Thanks for the info. I'll try to test it the same way, with disabled Ethereum, and will see what can be done and whether it affects anything else.

2024-01-30 11:05 UTC, merged